[package]
name = "dns"
version = "0.1.0"
edition = "2021"

# [lib]
# path = "source/library.rs"

[[bin]]
name = "dns"
path = "source/main.rs"

[dependencies]
bitvec = "1.0.1"
nix = { version = "0.29.0", features = ["socket", "net"] }
